# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
  en: Fogller Holdings
  iw: פוגלר החזקות
address:
  en: Hasadnaot 4, Herzliya
  iw: הסדנאות 4, הרצליה
email: office@fogller.com
phone:
  en: +972 09-9599016
  iw: 09-9599016
description:
  en: >- # this means to ignore newlines until new property
    Welcome to Fogller Holdings where we strive to see beyond the actual planning to provide our customers with a high quality of life for many years.<br>
    This strategy is reflected in each and every one of our projects, and is displayed in the detailed design and extra high standards we maintain - whether it is a building for conservation or an entire urban neighborhood.
  iw: >-
    את ההקפדה על הפרטים והעיצוב ניתן לראות בכל יוזמה של פוגלר החזקות, בין אם זה בניין בוטיק או רובע עירוני שלם. השאיפה להוביל דרך סטנדרטים גבוהים היא בבסיס התפיסה המקצועית של החברה. אסטרטגיית החברה ברורה בכל היבט ושואפת להביט מעבר לתכניות מתוך רצון ליצור איכות חיים גבוהה לאורך שנים רבות.
photos:
  -
    - Jaffa-1-Hanan-54-cropped.jpg
    - Faltaden SYSTEM_Baiersbronn-3.jpg
    - shimon-c02_00000.jpg
    - IMG_2697.jpg
    - Jaffa-1-Hanan-59.jpg
    - 1.jpg
    - Ertog_Taza_01_P.jpg
    - Jaffa-1-Hanan-04.jpg
    - Jaffa-1-Hanan-18.jpg
    - simulation-2-commerce-laundry.jpg
    - Jaffa-1-Hanan-20.jpg
    - simulation-iger.jpg
    - Scene_2_2014_11_03_HR.jpg
    - shuk-yavne-shtila-09842_0.jpg
    - Jaffa-1-Hanan-10.jpg
    - Ana Frank 1.jpg
    - Jaffa-1-Hanan-19.jpg
    - shimon-c01_00000.jpg
    - Jaffa-1-Hanan-58.jpg
    - shimon-apart3floor-c02_0.jpg
    - Jaffa-1-Hanan-11.jpg
    - Jaffa-1-Hanan-21.jpg
    - Jaffa-1-Hanan-58.jpg
    - Jaffa-1-Hanan-05.jpg
    - Jaffa-1-Hanan-22.jpg
    - Jaffa-1-Hanan-48.jpg
    - Jaffa-1-Hanan-03.jpg
    - Jaffa-1-Hanan-26.jpg
    - Jaffa-1-Hanan-24.jpg
    - Jaffa-1-Hanan-25.jpg
    - Jaffa-1-Hanan-17.jpg
    - shimon-penthouse-c02_0.jpg
    - Jaffa-1-Hanan-47.jpg
    - Scene_1_2014_11_04_HR.jpg
    - Jaffa-1-Hanan-56.jpg
    - patio-render.jpg
    - Jaffa-1-Hanan-23.jpg
    - shimon-penthouse-c03_0.jpg
    - shimon-c03_00000.jpg
    - Jaffa-1-Hanan-16.jpg
    - Jaffa-1-Hanan-46.jpg
    - shuk-yavne-op1-c01_00000.jpg
    - Jaffa-1-Hanan-06.jpg
    - shimon-penthouse-c01_0.jpg
    - shuk-yevani-shtila-09842_00000.jpg
    - Jaffa-1-Hanan-27.jpg
    - simulation-1-commerce.jpg
    - Jaffa-1-Hanan-09.jpg
  -
    - IMG_2697.jpg
    - Jaffa-1-Hanan-59.jpg
    - 1.jpg
    - Ertog_Taza_01_P.jpg
    - shuk-yavne-shtila-09842_0.jpg
    - Jaffa-1-Hanan-10.jpg
    - Jaffa-1-Hanan-19.jpg
    - Jaffa-1-Hanan-58.jpg
    - shimon-c01_00000.jpg
    - Jaffa-1-Hanan-58.jpg
    - Jaffa-1-Hanan-05.jpg
    - Jaffa-1-Hanan-54-cropped.jpg
    - Faltaden SYSTEM_Baiersbronn-3.jpg
    - shimon-c02_00000.jpg
    - Jaffa-1-Hanan-22.jpg
    - Jaffa-1-Hanan-48.jpg
    - Jaffa-1-Hanan-03.jpg
    - Ana Frank 1.jpg
    - Jaffa-1-Hanan-24.jpg
    - Jaffa-1-Hanan-25.jpg
    - Jaffa-1-Hanan-04.jpg
    - Jaffa-1-Hanan-47.jpg
    - Jaffa-1-Hanan-18.jpg
    - simulation-2-commerce-laundry.jpg
    - shimon-penthouse-c02_0.jpg
    - Scene_1_2014_11_04_HR.jpg
    - Jaffa-1-Hanan-56.jpg
    - patio-render.jpg
    - Jaffa-1-Hanan-21.jpg
    - Jaffa-1-Hanan-23.jpg
    - Jaffa-1-Hanan-20.jpg
    - Jaffa-1-Hanan-11.jpg
    - shimon-penthouse-c03_0.jpg
    - shimon-c03_00000.jpg
    - Jaffa-1-Hanan-09.jpg
    - simulation-1-commerce.jpg
    - Jaffa-1-Hanan-16.jpg
    - Jaffa-1-Hanan-27.jpg
    - Jaffa-1-Hanan-46.jpg
    - shuk-yevani-shtila-09842_00000.jpg
    - shuk-yavne-op1-c01_00000.jpg
    - shimon-penthouse-c01_0.jpg
    - Jaffa-1-Hanan-06.jpg
    -
    - shimon-apart3floor-c02_0.jpg
  -
    - Jaffa-1-Hanan-09.jpg
    - simulation-1-commerce.jpg
    - Jaffa-1-Hanan-27.jpg
    - shuk-yevani-shtila-09842_00000.jpg
    - shimon-penthouse-c01_0.jpg
    - Jaffa-1-Hanan-06.jpg
    - shuk-yavne-op1-c01_00000.jpg
    - Jaffa-1-Hanan-46.jpg
    - Jaffa-1-Hanan-16.jpg
    - shimon-c03_00000.jpg
    - shimon-penthouse-c03_0.jpg
    - Jaffa-1-Hanan-23.jpg
    - patio-render.jpg
    - Jaffa-1-Hanan-56.jpg
    - Scene_1_2014_11_04_HR.jpg
    - Jaffa-1-Hanan-47.jpg
    - shimon-penthouse-c02_0.jpg
    - Jaffa-1-Hanan-17.jpg
    - Jaffa-1-Hanan-25.jpg
    - Jaffa-1-Hanan-24.jpg
    - Jaffa-1-Hanan-26.jpg
    - Jaffa-1-Hanan-03.jpg
    - Jaffa-1-Hanan-48.jpg
    - Jaffa-1-Hanan-22.jpg
    - Jaffa-1-Hanan-05.jpg
    - Jaffa-1-Hanan-58.jpg
    - Jaffa-1-Hanan-21.jpg
    - Jaffa-1-Hanan-11.jpg
    - shimon-apart3floor-c02_0.jpg
    - Jaffa-1-Hanan-58.jpg
    - shimon-c01_00000.jpg
    - Jaffa-1-Hanan-19.jpg
    - Ana Frank 1.jpg
    - Jaffa-1-Hanan-10.jpg
    - shuk-yavne-shtila-09842_0.jpg
    - Scene_2_2014_11_03_HR.jpg
    - simulation-iger.jpg
    - Jaffa-1-Hanan-20.jpg
    - simulation-2-commerce-laundry.jpg
    - Jaffa-1-Hanan-18.jpg
    - Jaffa-1-Hanan-04.jpg
    - Ertog_Taza_01_P.jpg
    - 1.jpg
    - Jaffa-1-Hanan-59.jpg
    - IMG_2697.jpg
    - shimon-c02_00000.jpg
    - Faltaden SYSTEM_Baiersbronn-3.jpg
    - Jaffa-1-Hanan-54-cropped.jpg
# !!! don't forget change values of photosSizes in preparing images bash script !!!
photosSizes:
  - 2411
  - 1920
  - 1366
  - 960
index:
  iw: ''
  en: en.html

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
